---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark-role
  namespace: rhods-notebooks
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - services
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark-serviceaccount_name
  namespace: rhods-notebooks
subjects:
  - kind: ServiceAccount
    name: serviceaccount_name
    namespace: rhods-notebooks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-role

